import type { StandardOrderState } from "./types.js";

const TRANSITIONS: Readonly<Record<StandardOrderState, readonly StandardOrderState[]>> = {
  DRAFT: ["CHALLENGE_ISSUED"],
  CHALLENGE_ISSUED: ["ATTEMPT_OPENED", "NO_REFUND"],
  ATTEMPT_OPENED: ["VERIFIED", "VERIFY_REJECTED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NO_REFUND"],
  VERIFIED: ["SETTLE_INVOKED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NO_REFUND"],
  VERIFY_REJECTED: ["EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NO_REFUND"],
  SETTLE_INVOKED: ["FACILITATOR_CONFIRMED", "SETTLEMENT_AMBIGUOUS", "SETTLEMENT_FAILED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "NO_REFUND"],
  FACILITATOR_CONFIRMED: ["DEPOSIT_FINAL", "LEGAL_HOLD", "REFUND_DUE", "NO_REFUND"],
  SETTLEMENT_AMBIGUOUS: ["FACILITATOR_CONFIRMED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "REFUND_DUE", "NO_REFUND"],
  SETTLEMENT_FAILED: ["EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NO_REFUND"],
  EXTERNAL_OR_UNPROVEN_DEPOSIT: ["FACILITATOR_CONFIRMED", "LEGAL_HOLD"],
  DEPOSIT_FINAL: ["RELEASE_FINAL", "LEGAL_HOLD", "REFUND_DUE"],
  RELEASE_FINAL: ["DISPATCH_STARTED", "PROVIDER_FAILED", "LEGAL_HOLD", "REFUND_DUE"],
  DISPATCH_STARTED: ["DISPATCHED", "DISPATCH_AMBIGUOUS"],
  DISPATCHED: ["FULFILLED", "PROVIDER_FAILED", "INPUT_REQUIRED", "LEGAL_HOLD", "REFUND_DUE"],
  DISPATCH_AMBIGUOUS: ["DISPATCHED", "PROVIDER_FAILED", "LEGAL_HOLD", "REFUND_DUE"],
  FULFILLED: ["REFUND_DUE", "LEGAL_HOLD", "NO_REFUND"],
  PROVIDER_FAILED: ["REFUND_DUE", "LEGAL_HOLD", "NO_REFUND"],
  INPUT_REQUIRED: ["DISPATCHED", "PROVIDER_FAILED", "LEGAL_HOLD", "REFUND_DUE"],
  LEGAL_HOLD: [],
  REFUND_DUE: ["REFUND_RESERVED", "LEGAL_HOLD"],
  REFUND_RESERVED: ["REFUND_INVOKED", "LEGAL_HOLD"],
  REFUND_INVOKED: ["REFUNDED", "REFUND_AMBIGUOUS"],
  REFUND_AMBIGUOUS: ["REFUNDED", "LEGAL_HOLD"],
  REFUNDED: [],
  NO_REFUND: [],
};

export function assertTransition(from: StandardOrderState, to: StandardOrderState): void {
  if (!TRANSITIONS[from].includes(to)) {
    throw new Error(`Forbidden standard-order transition ${from} -> ${to}`);
  }
}

export function isTerminalState(state: StandardOrderState): boolean {
  return TRANSITIONS[state].length === 0;
}
