import type { StandardOrderState } from "./types.js";

const TRANSITIONS: Readonly<Record<StandardOrderState, readonly StandardOrderState[]>> = {
  DRAFT: ["CHALLENGE_ISSUED"],
  CHALLENGE_ISSUED: ["ATTEMPT_OPENED", "NOT_SETTLED"],
  ATTEMPT_OPENED: ["VERIFIED", "VERIFY_REJECTED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NOT_SETTLED"],
  VERIFIED: ["SETTLE_INVOKED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NOT_SETTLED"],
  VERIFY_REJECTED: ["EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NOT_SETTLED"],
  SETTLE_INVOKED: ["FACILITATOR_CONFIRMED", "SETTLEMENT_AMBIGUOUS", "SETTLEMENT_FAILED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "NOT_SETTLED"],
  FACILITATOR_CONFIRMED: ["DEPOSIT_FINAL", "LEGAL_HOLD", "NOT_SETTLED"],
  SETTLEMENT_AMBIGUOUS: ["FACILITATOR_CONFIRMED", "EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NOT_SETTLED"],
  SETTLEMENT_FAILED: ["EXTERNAL_OR_UNPROVEN_DEPOSIT", "LEGAL_HOLD", "NOT_SETTLED"],
  EXTERNAL_OR_UNPROVEN_DEPOSIT: ["FACILITATOR_CONFIRMED", "LEGAL_HOLD"],
  DEPOSIT_FINAL: ["RELEASE_FINAL", "LEGAL_HOLD"],
  RELEASE_FINAL: ["DISPATCH_STARTED", "PROVIDER_FAILED", "LEGAL_HOLD"],
  DISPATCH_STARTED: ["DISPATCHED", "DISPATCH_AMBIGUOUS"],
  DISPATCHED: ["FULFILLED", "PROVIDER_FAILED", "INPUT_REQUIRED", "LEGAL_HOLD"],
  DISPATCH_AMBIGUOUS: ["DISPATCHED", "PROVIDER_FAILED", "LEGAL_HOLD"],
  FULFILLED: [],
  PROVIDER_FAILED: [],
  INPUT_REQUIRED: ["DISPATCHED", "PROVIDER_FAILED", "LEGAL_HOLD"],
  LEGAL_HOLD: [],
  NOT_SETTLED: [],
};

export function assertTransition(from: StandardOrderState, to: StandardOrderState): void {
  if (!TRANSITIONS[from].includes(to)) {
    throw new Error(`Forbidden standard-order transition ${from} -> ${to}`);
  }
}

export function isTerminalState(state: StandardOrderState): boolean {
  return TRANSITIONS[state].length === 0;
}
